// Forever Mage Lab: the class data object. Everything class-specific the page engine reads lives here.
// A new class forks the repo and replaces this file (plus data/talents.json and the icon list), not the engine.
// Sources: data/talents.json (trees and talents, inlined by src/build.py, never retyped here), the Mage research notes
// (talents FINDINGS section 4 for racials, spells NOTES section (b) for trainer levels), and Wowhead Forever tooltip
// JSON for icon names.
// Page text: every number in it comes from a command in README.md ("How to reproduce each claim"), run on 1 Oct 2026.
// Leveling numbers: python analysis/leveling_paths.py [section]. Raid: python analysis/raid_specs.py and raid_check.py.
(function (root) {
  'use strict';
  const inNode = typeof module !== 'undefined';
  const talentData = inNode ? require('../data/talents.json') : root.FML_TALENT_DATA;
  const talentText = inNode ? {} : (root.FML_TALENT_TEXT || {});
  const REPO = 'https://github.com/opitaru-sys/forever-mage-lab';

  // ---------------------------------------------------------------- AoE leveling: the one place to swap the AoE wording
  // The final wording (1 Oct 2026, 15:39 report), from mage-research/aoe/aoe_v1.txt; numbers: python analysis/aoe_breakeven.py.
  // The short answer (text.verdict, id v-aoe) and the AoE claim (claims, id c-aoe) both read from here.
  // README.md carries the same verdict and the breakeven summary.
  const AOE = {
    verdict: '**No, not in our model.** At every level we tested, against mobs of your level, Blizzard, Arcane Explosion and Flamestrike pulls of 2 to 10 mobs fail: most run out of mana, and the rest are caught before Frost Nova is back. Two mobs at once, with Frost Nova and Frostbolt, are about even with one at a time at 50 and 60 and slower below.',
    title: 'AoE leveling does not pay in Forever, in our model',
    body: [
      'Classic Mages leveled by gathering a pack, freezing it and burning it down with Blizzard. At every level we tested (20, 25, 30, 40, 50 and 60), against mobs of your level, that loop does not pay in Forever: no Blizzard, Arcane Explosion or Flamestrike pull of 2 to 10 mobs survives with a quarter of your health to spare. Blizzard\'s chill is the reason. Forever\'s client gives it 50% for 2 seconds, against Classic\'s 75% for 4.5. A pack walks out of the storm in about 4 seconds, so only 3 to 6 of a Blizzard\'s 8 ticks land on each mob, while every mob needs about three full Blizzards. Most failed pulls run out of mana; the rest are caught before Frost Nova is back.',
      'Two mobs at once, with Frost Nova and Frostbolt, comes closest: about even with one at a time at 50 and 60, within the model\'s 6 to 9% slow bias there, and 9 to 45% slower per kill from 20 to 40. We tested every uncertain number at its low and high, plus a Frost Nova that never breaks and mobs 3 levels below you, and none clearly flips the answer alone. The only pair that clearly does is a Classic-strength chill together with mobs hitting half as hard as we assume: big Blizzard pulls then pay, from 5 to 7 mobs at 40 to 60.',
      'What would change it: [test m3](#t3) (Blizzard\'s chill), [test m16](#t16) (mob damage), [test m20](#t20) (how often two mobs stand close enough to pull together, which moves two mobs at 60 from 2% ahead to 13% behind) and [test m12](#t12) (how often damage breaks Frost Nova, which moves small pulls 5 to 20 points but flips nothing).',
    ],
    method: 'The AoE model plays pulls of 2 to 10 mobs of your level in 0.1 second steps, at 20, 25, 30, 40, 50 and 60, with the pack as groups of mobs that freeze, break free and run at you, through five scripted loops (two mobs with Frost Nova and Frostbolt, Blizzard, Arcane Explosion, Flamestrike and Cone of Cold kiting), and compares seconds per kill with the single-target model. On one mob it runs 3 to 9% slower than the single-target model, never faster, so it errs against AoE. A separate Claude session reviewed it.',
    limits: 'AoE adds: no server target cap ([m1](#t1)), Blizzard ticks that never crit ([m9](#t9)), beast packs that never flee ([m20](#t20)), free gathering, and a 25% health safety margin.',
  };

  const CLASS = {
    id: 'mage',
    name: 'Mage',
    title: 'Forever Mage Lab',
    icon: 'classicon_mage',
    repoUrl: REPO,
    liveUrl: 'https://opitaru-sys.github.io/forever-mage-lab/',
    resultsUrl: REPO + '/issues/new?template=test-result.yml',
    correctionUrl: REPO + '/issues/new?template=correction.yml',
    storagePrefix: 'fml.',
    // the class switch in the header. A sibling page reads #go-<race>-<level>, or #go-<level> when it lacks the race.
    siblings: [
      { id: 'warlock', name: 'Warlock', url: 'https://opitaru-sys.github.io/forever-warlock-lab/', icon: 'classicon_warlock',
        races: ['human', 'gnome', 'orc', 'troll', 'undead'] },
    ],

    // CSS custom properties. Contrast checked (WCAG): text pairs at least 4.6:1 in light and 6.0:1 in dark mode.
    colors: {
      light: { accent: '#2F4FAE', 'accent-ink': '#FFFFFF', 'accent-soft': '#E4E9F7', bar: '#2F4FAE',
        tree0: '#8E3AA6', 'tree0-soft': '#F3E6F7', tree1: '#B8440F', 'tree1-soft': '#FBE9DF', tree2: '#0B6A9A', 'tree2-soft': '#DDEFF8' },
      dark: { accent: '#86A6F2', 'accent-ink': '#0C0E13', 'accent-soft': '#1C2540', bar: '#86A6F2',
        tree0: '#D59AE8', 'tree0-soft': '#2E1C36', tree1: '#F2995E', 'tree1-soft': '#3A2214', tree2: '#6CC6EE', 'tree2-soft': '#12293A' },
    },

    // ---------------------------------------------------------------- talents (CONTRACTS section 1)
    trees: talentData.trees,
    talents: talentData.talents,
    talentText,                       // {key: [text at rank 1, rank 2, ...]}, derived by build.py from data/mage_talents_research.json
    talentRules: { trees: 3, rows: 7, perRow: 5, firstLevel: 10, maxLevel: 60, gears: [1, 2] },
    treeIcons: ['spell_holy_magicalsentry', 'spell_fire_flamebolt', 'spell_frost_frostbolt02'],
    talentIcons: {
      WandSpecialization: 'inv_wand_01', ArcaneFocus: 'spell_holy_devotion', ImprovedChanneling: 'spell_nature_starfall',
      ArcaneSubtlety: 'spell_holy_dispelmagic', MagicAbsorption: 'spell_nature_astralrecalgroup', ArcaneConcentration: 'spell_shadow_manaburn',
      ArcaneResilience: 'spell_arcane_arcaneresilience', ArcaneGeometry: 'inv_ability_mage_radiantspark', ArcaneImpact: 'spell_nature_wispsplode',
      ArcaneBlast: 'spell_arcane_blast', ArcaneShielding: 'spell_shadow_detectlesserinvisibility', ImprovedCounterspell: 'spell_frost_iceshock',
      ArcaneMeditation: 'spell_shadow_siphonmana', MissileBarrage: 'ability_mage_missilebarrage', PresenceOfMind: 'spell_nature_enchantarmor',
      ArcaneMind: 'spell_shadow_charm', ArcaneInstability: 'spell_shadow_teleport', ArcanePower: 'spell_nature_lightning',
      WakeOfFire: 'spell_fire_lavaspawn', Incineration: 'spell_fire_flameshock', ImprovedFireball: 'spell_fire_flamebolt',
      Ignite: 'spell_fire_incinerate', FlameThrowing: 'spell_fire_flare', Impact: 'spell_fire_meteorstorm',
      BurningSoul: 'spell_fire_fire', ImprovedFlamestrike: 'spell_fire_selfdestruct', Pyroblast: 'spell_fire_fireball02',
      ImprovedScorch: 'spell_fire_windsofwoe', ImprovedFireWard: 'spell_fire_firearmor', HotStreak: 'ability_mage_hotstreak',
      MasterOfElements: 'spell_fire_masterofelements', CriticalMass: 'spell_nature_wispheal', BlastWave: 'spell_holy_excorcism_02',
      FirePower: 'spell_fire_immolation', Combustion: 'spell_fire_sealoffire',
      FrostWarding: 'spell_frost_frostward', ImprovedFrostbolt: 'spell_frost_frostbolt02', ElementalPrecision: 'spell_ice_magicdamage',
      IceShards: 'spell_frost_iceshard', Permafrost: 'spell_frost_wisp', ImprovedFrostNova: 'spell_frost_freezingbreath',
      Frostbite: 'spell_frost_frostarmor', PiercingIce: 'spell_frost_frostbolt', FrostChanneling: 'spell_frost_stun',
      IceLance: 'spell_frost_frostblast', ImprovedBlizzard: 'spell_frost_icestorm', ArcticReach: 'spell_shadow_darkritual',
      IceBlock: 'spell_frost_frost', Shatter: 'spell_frost_frostshock', ImprovedConeOfCold: 'spell_frost_glacier',
      ColdSnap: 'spell_frost_wizardmark', FingersOfFrost: 'ability_mage_wintersgrasp', WintersChill: 'spell_frost_chillingblast',
      IceBarrier: 'spell_ice_lament',
    },
    // talent cell labels: shortened words, and soft hyphens (U+00AD) as clean break points in the small cells
    shortReplace: [['Improved ', 'Imp. ']],
    shortWords: {
      Specialization: 'Special\u00ADization', Channeling: 'Chan\u00ADneling', Subtlety: 'Subt\u00ADlety', Absorption: 'Absorp\u00ADtion',
      Concentration: 'Concen\u00ADtration', Resilience: 'Resil\u00ADience', Geometry: 'Geo\u00ADmetry', Shielding: 'Shield\u00ADing',
      Counterspell: 'Counter\u00ADspell', Meditation: 'Medi\u00ADtation', Barrage: 'Bar\u00ADrage', Presence: 'Pres\u00ADence',
      Instability: 'Insta\u00ADbility', Incineration: 'Incin\u00ADeration', Fireball: 'Fire\u00ADball', Throwing: 'Throw\u00ADing',
      Flamestrike: 'Flame\u00ADstrike', Pyroblast: 'Pyro\u00ADblast', Elements: 'Ele\u00ADments', Critical: 'Criti\u00ADcal',
      Combustion: 'Combus\u00ADtion', Warding: 'Ward\u00ADing', Frostbolt: 'Frost\u00ADbolt', Elemental: 'Ele\u00ADmental',
      Precision: 'Preci\u00ADsion', Permafrost: 'Perma\u00ADfrost', Frostbite: 'Frost\u00ADbite', Blizzard: 'Bliz\u00ADzard',
    },

    // ---------------------------------------------------------------- races (CONTRACTS section 5, FINDINGS section 4)
    // racials: [name, Forever effect, icon]. Skyborne is Skyborne High Order.
    // level and levelPct: time from 10 to 60 against no racials, planner build, gear 1 (leveling_paths.py races).
    // Raid percentages in the verdicts: the top build at the calculator defaults (the page computes the live number).
    // pvp: the racial's own tooltip effect only; nothing here ranks races for PvP, because no source does.
    races: {
      human: { label: 'Human', faction: 'Alliance', icon: 'race_human_male', note: '',
        racials: [['Sword Specialization', '+2% crit with spells and attacks while a sword is equipped. Mages can use one-hand swords.', 'ability_meleedamage'],
                  ['The Human Spirit', '+5% Spirit.', 'inv_enchant_shardbrilliantsmall'],
                  ['Will to Survive', 'Remove stuns. 3 min cooldown.', 'spell_shadow_charm']],
        level: 'About 1% faster: +5% Spirit, and +2% crit with a sword in hand from 21', levelPct: 1.1,
        pvp: ['Will to Survive', 'removes stuns, 3 min cooldown'],
        verdict: 'The second-best raid race, +1.4% with a sword in hand, and about 1% faster leveling.',
        tip: 'From 21, get the Coldflame Saber: Shadowfang Keep\'s Blade of Silverlaine plus the Scroll of the Saber (a Comprehension scroll) make a Mage sword with +32 spell power and +7 Intellect, and it switches on your +2% crit.',
        raidNote: 'With a sword in hand (the calculator\'s sword switch). Over no racials, top build.' },
      gnome: { label: 'Gnome', faction: 'Alliance', icon: 'race_gnome_male', note: '',
        racials: [['Expansive Mind', '+5% max mana. In Classic it was +5% Intellect.', 'inv_enchant_essenceeternallarge'],
                  ['Eureka!', 'Your next 3 damaging abilities cost 10% less mana and deal 10% more damage, but not to damage over time; channeled spells such as Arcane Missiles still count. 2 min cooldown. Before beta build 70009 the Mage version cut the cost by 50%.', 'inv_gnometoy'],
                  ['Escape Artist', 'Remove slows and roots, then 3 sec of immunity to them. 2 min cooldown.', 'ability_rogue_trip']],
        level: 'Under 1% faster: +5% max mana, and Eureka! on the pull', levelPct: 0.9,
        pvp: ['Escape Artist', 'removes roots and slows, 2 min cooldown'],
        verdict: 'A small edge everywhere: under 1% faster leveling and +0.7% in raids.',
        tip: 'Press Eureka! on the pull: your next 3 damaging spells cost 10% less and deal 10% more, though not on damage over time. It is back every 2 minutes.',
        raidNote: '' },
      skyborne: { label: 'Skyborne', fullName: 'Skyborne High Order', faction: 'Alliance', icon: 'race_skyborne_male',
        note: 'Needs a Heroic or higher pack. The Horde Skyborne, the Windshapers, cannot be Mages.',
        racials: [['Wind Blessed', '+1% haste (cast speed).', 'inv_misc_volatileair'],
                  ['Elemental Insight', '+5% damage against Elementals.', 'achievement_raidprimalist_windelemental'],
                  ['Read Ley Line', 'Health and mana regen +100% for 15 sec, or for 15 min near a ley line. 2 sec cast, 2 min cooldown.', 'ability_mage_incantersabsorbtion']],
        level: 'About 2% faster: 1% haste, Read Ley Line while resting, and +5% on elementals', levelPct: 1.9,
        pvp: ['No escape racial', 'its racials are haste, damage on elementals and regen'],
        verdict: 'The second-fastest leveler, about 2%, and +0.7% in raids. Needs a Heroic pack.',
        tip: 'Cast Read Ley Line when you sit down to rest: it doubles your health and mana regen for 15 seconds, or 15 minutes near a ley line. The model counts it on Spirit regen only, not on your drink.',
        raidNote: '' },
      orc: { label: 'Orc', faction: 'Horde', icon: 'race_orc_male', note: 'New for Mages in Forever.',
        racials: [['Blood Fury', '+10% attack power and spell power for 15 sec. 2 min cooldown.', 'racial_orc_berserkerstrength'],
                  ['Shatter Curse', 'Remove curses and banes, and take 15% less magic damage for 8 sec. 3 min cooldown.', 'spell_nature_removecurse'],
                  ['Hardiness', 'Stuns on you last 20% shorter.', 'inv_helmet_23'],
                  ['Axe Specialization', '+1% crit with an axe. Mages cannot equip axes.', 'inv_axe_02']],
        level: 'Under 0.5% faster: Blood Fury on the pull, every 2 minutes', levelPct: 0.4,
        pvp: ['Hardiness', 'stuns on you last 20% shorter'],
        verdict: 'New to Mages in Forever: the smallest leveling edge, and +0.7% in raids.',
        tip: 'Use Blood Fury on the pull: +10% spell power for 15 seconds, every 2 minutes. Axe Specialization does nothing for you, since Mages cannot equip axes.',
        raidNote: '' },
      undead: { label: 'Undead', faction: 'Horde', icon: 'race_scourge_male', note: '',
        racials: [['Touch of the Grave', 'Caster version: your spells and attacks have a 10% chance to drain 5% of your max health from the target, at most once per second. By the game\'s data that includes wand shots (test m23).', 'spell_shadow_fingerofdeath'],
                  ['Cannibalize', '7% health and 7% mana every 2 sec for 10 sec, from a humanoid or undead corpse. 2 min cooldown. In Classic it restored health only.', 'ability_racial_cannibalize'],
                  ['Will of the Forsaken', 'Remove charm, fear and sleep. 2 min cooldown.', 'spell_shadow_raisedead']],
        level: 'About 3% faster, the most of any race: Touch of the Grave on your spells and wand shots, and Cannibalize now restores mana too', levelPct: 3.2,
        pvp: ['Will of the Forsaken', 'removes charm, fear and sleep, 2 min cooldown'],
        verdict: 'The best Mage race by small margins: about 3% faster leveling, and the biggest raid racial, +1.6%.',
        tip: 'Cannibalize a humanoid or undead corpse when you sit down: in Forever it restores mana as well as health. Touch of the Grave procs on wand shots too, so your wand finish heals you.',
        raidNote: 'Touch of the Grave at the calculator\'s max health (4000 is an assumption). Over no racials, top build.' },
      troll: { label: 'Troll', faction: 'Horde', icon: 'race_troll_male', note: '',
        racials: [['Berserking', '+10% casting and attack speed for 10 sec. 3 min cooldown. A flat 10%: in Classic it scaled from 10 to 30% with missing health.', 'racial_troll_berserk'],
                  ['Beast Slaying', '+5% damage against Beasts.', 'inv_misc_pelt_bear_ruin_02'],
                  ['Rapid Regeneration', 'Regain 50% of max health over a 6 sec channel. 3 min cooldown.', 'ability_racial_regeneratin'],
                  ['Regeneration', 'Health regen +10%, and 10% of it continues in combat.', 'spell_nature_regenerate']],
        level: 'About 1.3% faster: Beast Slaying, Berserking, and Rapid Regeneration while resting', levelPct: 1.3,
        pvp: ['Rapid Regeneration', '50% of your health over a 6 sec channel, 3 min cooldown'],
        verdict: 'A small leveling edge, about 1.3%, and the smallest raid racial, +0.5%.',
        tip: 'Berserking is a flat +10% cast speed in Forever, so press it on the pull instead of saving it for low health. Rapid Regeneration heals half your health between pulls.',
        raidNote: '' },
    },
    defaultRace: 'human',

    // icons for spells named in the planner's rotation steps and elsewhere
    spellIcons: {
      Frostbolt: 'spell_frost_frostbolt02', Fireball: 'spell_fire_flamebolt', 'Arcane Missiles': 'spell_nature_starfall',
      'Fire Blast': 'spell_fire_fireball', 'Frost Nova': 'spell_frost_frostnova', 'Cone of Cold': 'spell_frost_glacier',
      Blizzard: 'spell_frost_icestorm', 'Arcane Explosion': 'spell_nature_wispsplode', Flamestrike: 'spell_fire_selfdestruct',
      Scorch: 'spell_fire_soulburn', Pyroblast: 'spell_fire_fireball02', 'Arcane Blast': 'spell_arcane_blast',
      'Ice Lance': 'spell_frost_frostblast', 'Frostfire Bolt': 'ability_mage_frostfirebolt', 'Blast Wave': 'spell_holy_excorcism_02',
      Evocation: 'spell_nature_purge', 'Mage Armor': 'spell_magearmor', 'Arcane Intellect': 'spell_holy_magicalsentry',
      Wand: 'ability_shootwand',
    },

    // ---------------------------------------------------------------- dungeons (world data, copied from the Warlock page)
    // name, from, to, zone, home side, new in Forever. New dungeons use published ranges (Excavation Site: Wetlands 26 to 31
    // from Blizzard's 1 Oct 2026 notes); returning dungeons use an estimate around Forever's recommended level. Keep the
    // list sorted by `from`: the dungeon chart's "Next up" takes the first match in this order.
    dungeons: [
      ['Ragefire Chasm', 13, 18, 'Orgrimmar', 'Horde', false], ['Hall of Thanes', 13, 18, 'Ironforge', 'Alliance', true],
      ['Ruins of Lordaeron', 15, 20, 'Tirisfal Glades', 'Horde', true], ['The Deadmines', 16, 22, 'Westfall', 'Alliance', false],
      ['Wailing Caverns', 17, 23, 'The Barrens', 'Horde', false], ['Shadowfang Keep', 18, 24, 'Silverpine Forest', 'Horde', false],
      ['Blackfathom Deeps', 22, 28, 'Ashenvale', 'Both', false], ['Stormwind Stockade', 23, 28, 'Stormwind City', 'Alliance', false],
      ['Razorfen Kraul', 24, 30, 'The Barrens', 'Horde', false], ['Gnomeregan', 25, 31, 'Dun Morogh', 'Alliance', false],
      ['Excavation Site: Wetlands', 26, 31, 'Wetlands', 'Both', true], ['City of Dalaran', 28, 33, 'Alterac Mountains', 'Both', true],
      ['Scarlet Monastery', 30, 38, 'Tirisfal Glades', 'Both', false], ['Razorfen Downs', 34, 40, 'The Barrens', 'Horde', false],
      ['Uldaman', 35, 41, 'Badlands', 'Both', false], ['The Drowned City', 35, 40, 'Stranglethorn Vale', 'Both', true],
      ["Krol'dok Stronghold", 40, 45, 'Riverglades', 'Both', true], ["Zul'Farrak", 42, 48, 'Tanaris', 'Both', false],
      ['Maraudon', 42, 48, 'Desolace', 'Both', false], ["The Temple of Atal'Hakkar", 45, 51, 'Swamp of Sorrows', 'Both', false],
      ['Alcaz Prison', 48, 53, 'Dustwallow Marsh', 'Both', true], ['Blackrock Depths', 48, 56, 'Burning Steppes', 'Both', false],
      ['Lower Blackrock Spire', 53, 60, 'Burning Steppes', 'Both', false], ['Upper Blackrock Spire', 55, 60, 'Burning Steppes', 'Both', false],
      ['Dire Maul', 54, 60, 'Feralas', 'Both', false], ['Blackmaw Hold', 55, 60, 'zone unconfirmed', 'Both', true],
      ['Stratholme', 55, 60, 'Eastern Plaguelands', 'Both', false], ['Scholomance', 57, 60, 'Western Plaguelands', 'Both', false],
      ["Shaper's Terrace", 58, 60, "Un'Goro Crater", 'Both', true],
    ],

    // ---------------------------------------------------------------- level planner
    planner: {
      // The leveling model's planner order (python analysis/leveling_planner.py; PLANNER in analysis/leveling_paths.py),
      // legal at every level (commit 1951525, after the Permafrost fix). Final split 10 Arcane, 6 Fire, 35 Frost. Arcane
      // Concentration (54 to 58) makes 60 2.2% faster; Wand Specialization, Arcane Focus and Improved Cone of Cold change nothing there.
      order: [['ImprovedFrostbolt', 5], ['Frostbite', 2], ['IceShards', 2], ['Frostbite', 1], ['IceLance', 1], ['PiercingIce', 3],
        ['IceShards', 1], ['Shatter', 3], ['IceShards', 2], ['FingersOfFrost', 2], ['FrostChanneling', 2],
        ['ElementalPrecision', 1], ['FrostChanneling', 1], ['ElementalPrecision', 1], ['Incineration', 1],
        ['ElementalPrecision', 1], ['Incineration', 2], ['ArcticReach', 1], ['WintersChill', 1], ['ArcticReach', 1],
        ['WakeOfFire', 2], ['WintersChill', 2], ['Ignite', 1], ['WandSpecialization', 2], ['ArcaneFocus', 3],
        ['ArcaneConcentration', 5], ['ImprovedConeOfCold', 2]],
      respec: null,     // the one-respec plan (Arcane to 19) saves 0.36% of leveling time: not offered
      chips: [10, 20, 30, 40, 50, 60],
      // phases: the entry with the highest `from` at or below the level applies. steps are spellIcons names.
      // extra: optional [label, value, sub] shown as a fourth fact (the Warlock card's Pet slot).
      // Rotations: python analysis/leveling_paths.py phases (planner build, gear 1). Potions: ... consumables.
      phases: [
        { from: 1, name: 'Starting out', rot: 'Your newest damage spell, then the wand',
          sub: 'Below 10 the best pick changes with each new rank: Fireball, then Frostbolt at 4, Fireball rank 2 at 6, Arcane Missiles at 8. Finish with the wand once you have one.',
          steps: ['Fireball', 'Frostbolt', 'Wand'],
          extra: ['Mana', 'Drink between pulls', 'From 5, a Minor Mana Potion on cooldown, 40 copper each at the client\'s list price (no vendor is known; auction prices are likely far higher).'] },
        { from: 10, name: 'Frostbolt and wand', rot: 'Frostbolt, wand the last 20%',
          sub: 'Your first five talent points go to Improved Frostbolt. Frost Nova arrives at 10, but the model does not need it yet.',
          steps: ['Frostbolt', 'Wand'],
          extra: ['Mana', 'Minor Mana Potion on cooldown', 'One every 2 minutes: about 0.12 gold an hour at the client\'s list price (no vendor is known; auction prices are likely far higher), for kills 4.6% faster at 10. Over 10 to 60, potions cut leveling time by 9.2%.'] },
        { from: 14, name: 'Fire Blast joins', rot: 'Frostbolt, Fire Blast on cooldown, wand the last 20%',
          sub: 'Kills slow from about 26 to 33 seconds as the mobs outgrow your spells, until level 20. Frostbite and Ice Shards points come in.',
          steps: ['Frostbolt', 'Fire Blast', 'Wand'],
          extra: ['Mana', 'Lesser Mana Potion on cooldown', 'About 0.36 gold an hour at the client\'s list price (no vendor is known; auction prices are likely far higher), for kills 5 to 8% faster.'] },
        { from: 20, name: 'Freeze and lance', rot: 'Frostbolt; Frost Nova when the mob closes, then step back; Ice Lance on every freeze; wand the last 20%',
          sub: 'Level 20 is the big jump: about 33 seconds a kill at 19, 28 at 20, as Ice Lance, the third Frostbite point and Evocation arrive. Cast your highest Frostbolt rank. At 21, Frost Nova is within 1% either way (0.2%).',
          steps: ['Frostbolt', 'Frost Nova', 'Ice Lance', 'Wand'],
          extra: ['Mana', 'Lesser Mana Potion on cooldown', 'About 0.36 gold an hour at the client\'s list price (no vendor is known; auction prices are likely far higher). Evocation goes into rest when it saves time.'] },
        { from: 22, name: 'Freeze and lance', rot: 'Frostbolt; Frost Nova when the mob closes, then step back; Ice Lance on every freeze; wand the last 20%',
          sub: 'Kills hold at about 28 to 29 seconds through your 20s. At 22 the model adds Fire Blast on cooldown. At 24, filling with the wand and Fire Blast instead of Frostbolt is within 1% either way (0.4%). Cast your highest Frostbolt rank: Blizzard says ranks far below your level lose spell power and proc chance.',
          steps: ['Frostbolt', 'Frost Nova', 'Ice Lance', 'Wand'],
          extra: ['Mana', 'Mana Potion on cooldown', 'About 1.44 gold an hour at the client\'s list price (no vendor is known; auction prices are likely far higher), for kills 5 to 7% faster.'] },
        { from: 30, name: 'Fingers of Frost', rot: 'Frostbolt; Frost Nova when the mob closes, then step back; Ice Lance on every freeze and Fingers of Frost charge; wand the last 20%',
          sub: 'Fingers of Frost comes in at 30 and 31. Kills take about 24 to 26 seconds at 31 to 40. The model uses Frost Nova at every level but 33, steps back at 31, 34, 35 and 37 to 40, drops the wand finish at 35 to 37 (wand shots break roots too), weaves Fire Blast at 36, and adds a melee-range instant (Cone of Cold or Arcane Explosion) at 38 to 40. Wear Mage Armor from 34: with Frost or Ice Armor instead, the model levels 1.4% slower overall.',
          steps: ['Frostbolt', 'Frost Nova', 'Ice Lance', 'Wand'],
          extra: ['Mana', 'Mana Potion on cooldown, Greater from 31', 'About 1.44 gold an hour at the client\'s list price (no vendor is known; auction prices are likely far higher), for kills 7 to 9% faster.'] },
        { from: 41, name: 'No more wand', rot: 'Frostbolt, Fire Blast on cooldown; Frost Nova when the mob closes; Ice Lance on every freeze and Fingers of Frost charge',
          sub: 'From 41 the model drops the wand finish and the step back. Fire Blast on cooldown pays at 41 and 44 to 55; at 42 and 43 it costs 7.7% and 4.3%, so skip it there.',
          steps: ['Frostbolt', 'Fire Blast', 'Frost Nova', 'Ice Lance'],
          extra: ['Mana', 'Superior Mana Potion on cooldown', 'About 4.80 gold an hour at the client\'s list price (no vendor is known; auction prices are likely far higher), for kills about 10% faster.'] },
        { from: 49, name: 'No more wand', rot: 'Frostbolt, Fire Blast on cooldown; Frost Nova when the mob closes; Ice Lance on every freeze and Fingers of Frost charge',
          sub: 'Kills take about 20 to 21 seconds from 49 on, 19.8 at 60. Fire Blast on cooldown pays at 49 to 55; at 56 to 60 it is about even, within about 1% either way. Your points go to Arcane Concentration from 54: free spells on 10% of your hits, worth kills 2.2% faster at 60.',
          steps: ['Frostbolt', 'Fire Blast', 'Frost Nova', 'Ice Lance'],
          extra: ['Mana', 'Major Mana Potion on cooldown', 'About 18 gold an hour at the client\'s list price (no vendor is known; auction prices are likely far higher), for kills 8 to 14% faster.'] },
      ],
      // Gear: python analysis/leveling_paths.py phases prints gear 1 (spell power = level) and gear 2 (twice the level).
      gear: [
        { from: 1, text: '**Gear.** Spell power is what the leveling model measures: twice your level in spell power, instead of your level, makes kills about 10% faster in your teens. Wands no longer gain spell power in Forever, so upgrade the wand itself: the model finishes most mobs with it until 40.' },
        { from: 21, text: '**Gear.** From 21 the Coldflame Saber is a Mage sword: Shadowfang Keep\'s Blade of Silverlaine plus the Scroll of the Saber (a Comprehension scroll) give +32 spell power and +7 Intellect, and +2% crit for a Human. Keep the wand upgraded too: the model finishes most mobs with it until 40.' },
        { from: 41, text: '**Gear.** From 41 the model stops finishing with the wand, so spell power is the stat to chase. Twice your level in spell power, instead of your level, makes kills about 6% faster in your 40s and 3% faster in your 50s.' },
        { from: 60, text: '**Gear at 60.** The [raid calculator](#raid) prices every stat in spell power for each build, and the [item comparer](#upgrades) re-runs the full model for a swap.' },
      ],
      // Trainer levels by rank (spells/NOTES.md section (b), Wowhead tooltips for Mage Armor and Evocation).
      // Frostbolt rank 11, Fireball rank 12 and Arcane Missiles rank 8 come from tomes and are left out.
      // Talent spells list rank 1 at the talent's earliest level; it comes with the talent point, not the trainer.
      ranks: {
        'Fireball': { levels: [1, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60] },
        'Frostbolt': { levels: [4, 8, 14, 20, 26, 32, 38, 44, 50, 56] },
        'Fire Blast': { levels: [6, 14, 22, 30, 38, 46, 54] },
        'Arcane Missiles': { levels: [8, 16, 24, 32, 40, 48, 56] },
        'Frost Nova': { levels: [10, 26, 40, 54] },
        'Arcane Explosion': { levels: [14, 22, 30, 38, 46, 54] },
        'Flamestrike': { levels: [16, 24, 32, 40, 48, 56] },
        'Blizzard': { levels: [20, 28, 36, 44, 52, 60] },
        'Evocation': { levels: [20] },
        'Scorch': { levels: [22, 28, 34, 40, 46, 52, 58] },
        'Cone of Cold': { levels: [26, 34, 42, 50, 58] },
        'Mage Armor': { levels: [34, 46, 58] },
        'Frostfire Bolt': { levels: [40, 50, 60] },
        'Pyroblast': { levels: [20, 24, 30, 36, 42, 48, 54, 60], talent: 'Pyroblast' },
        'Arcane Blast': { levels: [20, 30, 40, 50, 60], talent: 'ArcaneBlast' },
        'Ice Lance': { levels: [20, 28, 34, 42, 48, 56], talent: 'IceLance' },
        'Blast Wave': { levels: [30, 36, 44, 52, 60], talent: 'BlastWave' },
      },
      tomeNote: 'Frostbolt rank 11, Fireball rank 12 and Arcane Missiles rank 8 come from tomes that drop in the world. Where they drop in Forever is not known yet.',
    },

    // ---------------------------------------------------------------- talent builder
    // presets: [{ id, label, order: [[talent key, points], ...] }], legal at every level. The page plan and the raid
    // model's SPECS are added by the builder itself. These are the tree-first orders FIRE and ARCANE from
    // analysis/leveling_paths.py (the best Fire-first and Arcane-first orders the leveling search found).
    presets: [
      { id: 'fire', label: 'Fire-first leveling', order: [['WakeOfFire', 2], ['Incineration', 3], ['Ignite', 5], ['Pyroblast', 1],
        ['BurningSoul', 1], ['ImprovedFireball', 1], ['BurningSoul', 2], ['HotStreak', 1], ['ImprovedScorch', 3],
        ['FlameThrowing', 1], ['CriticalMass', 3], ['FlameThrowing', 1], ['Impact', 1], ['FirePower', 4], ['ImprovedFireball', 1],
        ['Combustion', 1], ['FirePower', 1], ['MasterOfElements', 2], ['Impact', 1], ['ElementalPrecision', 1],
        ['MasterOfElements', 1], ['ElementalPrecision', 2], ['Impact', 1], ['ElementalPrecision', 2], ['ImprovedFireball', 1],
        ['BlastWave', 1], ['ImprovedFrostbolt', 1], ['WandSpecialization', 1], ['ImprovedFrostbolt', 4], ['PiercingIce', 1]] },
      { id: 'arcane', label: 'Arcane-first leveling', order: [['ImprovedChanneling', 1], ['WandSpecialization', 2],
        ['ArcaneFocus', 2], ['ArcaneConcentration', 4], ['ImprovedChanneling', 1], ['ArcaneFocus', 1], ['ArcaneConcentration', 1],
        ['ArcaneFocus', 1], ['ImprovedChanneling', 1], ['ArcaneBlast', 1], ['MissileBarrage', 1], ['ArcaneMeditation', 1],
        ['ArcaneImpact', 2], ['ArcaneMeditation', 1], ['PresenceOfMind', 1], ['ArcaneMeditation', 1], ['ArcaneImpact', 1],
        ['ArcaneMind', 2], ['ArcaneInstability', 3], ['ImprovedFrostbolt', 1], ['ImprovedChanneling', 2], ['ArcanePower', 1],
        ['ArcaneMind', 1], ['ImprovedFrostbolt', 1], ['ArcaneMind', 1], ['ElementalPrecision', 1], ['ArcaneMind', 1],
        ['ImprovedFrostbolt', 1], ['ElementalPrecision', 2], ['ImprovedFrostbolt', 2], ['ElementalPrecision', 2],
        ['FrostChanneling', 3], ['IceLance', 1], ['Permafrost', 1], ['Shatter', 1], ['ArcaneFocus', 1]] },
    ],
    builder: {
      gears: [[1, 'Leveling greens'], [2, 'Good gear for the level']],
      hpMults: [0.9, 1.0, 1.1],     // mob health 90%, 100% and 110%: kill time snaps to ticks otherwise
    },

    // ---------------------------------------------------------------- content
    // specCards: [{ name, sub, icon, build: {key: rank}, use, grey }]; the point split, talent list and builder link are generated.
    // The two group builds copy model.js SPECS (frost-mb, fire-mb): keep them in sync if the raid model changes its specs.
    specCards: [
      { name: 'Frost with Missile Barrage', sub: 'Group spec · raids · 534 dps at the calculator defaults, before racials', icon: 'ability_mage_missilebarrage',
        build: { ArcaneFocus: 5, ArcaneSubtlety: 2, ArcaneConcentration: 5, ArcaneImpact: 3, ArcaneMeditation: 2, MissileBarrage: 1,
          Incineration: 3, ImprovedFrostbolt: 5, ElementalPrecision: 5, IceShards: 5, PiercingIce: 3, FrostChanneling: 1, IceLance: 1,
          Shatter: 3, FingersOfFrost: 2, WintersChill: 5 },
        use: 'Use: Frostbolt, Ice Lance on every Fingers of Frost charge, and Arcane Missiles whenever Missile Barrage makes them free. 94 of its 534 dps are those free Missiles.',
        grey: 'Never short of mana at the defaults, so mp5 and Spirit add nothing to it. Ice Lance is 143 of its 534 dps, and both its spell power scaling and Fingers of Frost on bosses are untested (tests m4 and m30 below). Fights under about 85 seconds, such as many dungeon bosses, are a near tie with the sim\'s deep Fire build (0/35/16), which edges ahead by up to 2.5% in 60 second fights.' },
      { name: 'Fire with Arcane Blast', sub: 'Group alternative · 503 dps at the calculator defaults, before racials', icon: 'spell_fire_flamebolt',
        build: { ArcaneFocus: 5, ImprovedChanneling: 1, ArcaneConcentration: 5, ArcaneImpact: 3, ArcaneBlast: 1, ArcaneMeditation: 3,
          MissileBarrage: 1, Incineration: 3, ImprovedFireball: 5, Ignite: 5, BurningSoul: 1, Pyroblast: 1, ImprovedScorch: 3, HotStreak: 1,
          MasterOfElements: 3, CriticalMass: 3, FirePower: 5, Combustion: 1, ElementalPrecision: 1 },
        use: 'Use: one Arcane Blast before most Fireballs, Fire Blast on cooldown, Heating Up Pyroblasts and Ignite, plus free Arcane Missiles from Missile Barrage.',
        grey: 'It leads if Ice Lance has no spell power scaling or Fingers of Frost does not proc on bosses, by 1.6% over Arcane with Ignite. Shorter fights help it, but in a dice simulation it never passes Frost with Barrage at 60 seconds or longer; at 60 seconds they tie. With 1 point of Elemental Precision it gains most from hit gear: at 15% gear hit Frost leads by 2.5%. It is short of mana, so raid buffs and mp5 help it: no raid buffs costs it 8%. Out on a boss immune to Fire.' },
      { name: 'Frost for solo play', sub: 'Solo spec · questing and farming · the page plan at 60', icon: 'spell_frost_frostblast',
        build: { WandSpecialization: 2, ArcaneFocus: 3, ArcaneConcentration: 5, WakeOfFire: 2, Incineration: 3, Ignite: 1, ImprovedFrostbolt: 5, ElementalPrecision: 3, IceShards: 5, Frostbite: 3, PiercingIce: 3, FrostChanneling: 3, IceLance: 1, ArcticReach: 2, Shatter: 3, ImprovedConeOfCold: 2, FingersOfFrost: 2, WintersChill: 3 },
        use: 'Use: Frostbolt and Fire Blast on cooldown, Frost Nova when the mob closes, and Ice Lance on every freeze and Fingers of Frost charge. About 20 seconds a kill at 60 in the model.',
        grey: 'Arcane Concentration is the late talent that pays: 2.2% faster kills at 60. Wand Specialization and Arcane Focus are there to reach it, and Improved Cone of Cold changes nothing. No Ice Barrier: the model values Arcane Concentration more.' },
    ],

    // claims: [{ id: 'c-...', group: 'proof' | 'test' | 'bust' | 'known', title, body }]. Each ends with a link to its test,
    // its tool or the limits. Commands for every number: README.md, "How to reproduce each claim".
    claims: [
      { id: 'c-frost', group: 'proof', title: 'Frost levels fastest, under every assumption tested',
        body: ['Over levels 10 to 60 this page\'s order, Frost with 6 Fire and 10 Arcane points, kills a mob every 24.9 seconds on average, against 26.5 for the best Arcane-first order and 28.0 for the best Fire-first order. Weighted by the time each level takes, that is 104.4, 113.9 and 121.1 hours of grinding (kills only, no quest XP).',
          'Three things carry it. Ice Lance does four times the damage to a frozen target, and Shatter adds 50% crit against it. Frostbite and Fingers of Frost each turn 15% of your chills into a frozen target. And Frost Nova and Frostbite roots keep the mob out of melee, even though the model has damage break them half the time.',
          'A Frost-first order stayed first in all 19 sensitivity rows, including no stepping back after a root, Ice Lance with no spell power scaling, and no Spirit regen while drinking. The hours ride on the Warlock page\'s mob health and damage and an assumed XP per mob, so trust the comparison more than the hour count. [See the limits](#method).'] },
      { id: 'c-respec', group: 'proof', title: 'Starting Arcane and respeccing at 20 is not worth it',
        body: 'At levels 10 to 19 an Arcane wand build kills 3.8% faster than Frost (26.8 seconds against 27.9). But those levels are only 8.8% of the time from 10 to 60, so playing Arcane to 19 and the page plan from 20 saves 0.36%, about 22 minutes in 104 hours. Even switching to the best of four talent orders at every single level would save only 0.50%. The hours use the Classic XP table and an assumed 45 plus 5 x level XP a mob. [See the limits](#method).' },
      { id: 'c-lvl20', group: 'proof', title: 'Level 20 is the big jump',
        body: 'The page plan\'s kill time climbs from 23.7 seconds at 10 to 32.9 at 19, then drops to 28.2 at 20. Ice Lance, the third Frostbite point, Evocation and a better water all arrive at 19 or 20. From 20 the model plays Frostbolt, Frost Nova when the mob closes, a step back, and Ice Lance on every freeze; from 41 it drops the wand finish and the step back. It never picks a lower Frostbolt rank at 10 to 19, though it is allowed to. [Open the planner at 20](#lvl-20).' },
      { id: 'c-potions', group: 'proof', title: 'Mana potions save about 9% of your leveling time',
        body: ['With a mana potion on every 2 minute cooldown, the model levels 10 to 60 in 104.4 hours, against 114.9 without, 9.2% less. That is 30 potions an hour at every level, because every kill cycle is well under 2 minutes.',
          'At the client\'s list price that costs about 0.12 gold an hour at 10 to 13 (Minor), 0.36 at 14 to 21 (Lesser), 1.44 at 22 to 40 (Mana and Greater Mana), 4.80 at 41 to 48 (Superior) and 18 gold an hour from 49 (Major). No vendor is known to sell them, and auction prices are likely far higher. [Open the planner](#you).'] },
      { id: 'c-races', group: 'proof', title: 'Race barely matters',
        body: ['By time from 10 to 60, Undead levels 3.2% faster than no racials, Skyborne 1.9%, Troll 1.3%, Human 1.1%, Gnome 0.9% and Orc 0.4%. Undead gets it from Touch of the Grave, which procs on spells and wand shots alike (the tooltip says spells and attacks, and the game\'s data includes wand shots; spells only would make it 2.9%, test m23), and from Cannibalize, which restores mana in Forever. Some of it rests on assumptions: how many mobs are beasts, humanoids or elementals, and that Read Ley Line does not speed up drinks.',
          'In the raid calculator at its defaults, Undead adds 1.6% to the top build (with 4000 max health, an assumption you can change), a Human with a sword in hand 1.4%, and every other race 0.5 to 0.7%. [This is test m23](#t23).'] },
      { id: 'c-barrage', group: 'proof', title: 'The best raid builds all buy Missile Barrage',
        body: 'Missile Barrage sits 15 points into Arcane. With it, Arcane Blast (40%) and Fireball, Frostbolt or Frostfire Bolt (20%) can make your next Arcane Missiles free and twice as fast. 94 of Frost with Barrage\'s 534 dps are those free Missiles, and 75 of Fire with Arcane Blast\'s 503. The ElliotWood sim\'s own Frost and Fire builds skip it, and its three builds trail the best one by 9 to 21% at the same gear. [Try the raid calculator](#raid).' },
      { id: 'c-buffs', group: 'proof', title: 'Raid buffs matter more to Fire than to Frost',
        body: 'The calculator\'s raid buffs are Greater Blessing of Wisdom and Greater Blessing of Kings (one Blessing per Paladin, so a raid with two), Mana Spring Totem, Prayer of Spirit and Gift of the Wild. With them Frost with Barrage does 534 dps and Fire with Arcane Blast 503; with none, 515 and 462, which puts Fire with Arcane Blast behind both Arcane builds. They are worth about 4% to Frost and 9% to Fire, and Frost still leads. Kings alone is 0.4% of Frost\'s damage and 1.6% of Fire\'s. Without a Shaman in your group, Fire drops to 499. A Moonkin in your party is a separate switch, off by default: it adds 2 to 4% to every build and narrows Frost\'s lead to 5.1%. [Try the raid buff switches](#raid).' },
      { id: 'c-short', group: 'proof', title: 'In short fights the deep Fire build edges ahead',
        body: 'Under about 85 seconds the sim\'s deep Fire build (0/35/16) edges ahead, because its mana never runs short in a short fight: by 2.5% at 60 seconds in a dice simulation of 1000 fights, the better read here, and by under 2%, a tie, from about 75 seconds. The calculator puts the crossover at about 102 seconds, because it runs 3 to 7% high in 60 second fights, most for Fire. Fire with Arcane Blast closes in as fights get shorter but never passes Frost with Barrage in the dice: at 60 seconds they tie (513 against 515), and the calculator\'s crossover is about 93 seconds. Frost with Barrage is never short of mana, so it stays near 534 at any length; the Fire builds are, so shorter fights and more mp5 help them (at 120 mp5 from gear Frost leads Fire with Arcane Blast by 2.4%). Many dungeon bosses die inside 2 minutes. [Try the fight length slider](#raid).' },
      { id: 'c-spellblast', group: 'proof', title: 'Not short of mana? Drink the Spellblasting Potion',
        body: 'Builds that never run dry do better with the Major Spellblasting Potion (+47 spell damage for 30 seconds) than with the Major Mana Potion: Frost with Barrage 540 against 534, and Arcane 31/3/17 493 against 486. Fire with Arcane Blast and Arcane with Ignite want the mana potion. The two share one cooldown, and both cost gold. [Try the potion switch](#raid).' },
      { id: 'c-dice', group: 'proof', title: 'The calculator agrees with a cast-by-cast simulation',
        body: 'A separate script plays each build\'s plan cast by cast with real dice: every proc, stack ramps, the rolling Ignite, potion timing, 2 second mana ticks, the five-second rule and the wand. Over 1000 fights at the defaults it lands within 1% of the calculator for the four page builds (Frost with Barrage 531.5 against 534.2), and with mana unlimited every build agrees within 1.7%. Plans that wait for mana read 2 to 5% high in the calculator, and 60 second fights 3 to 7% high, most for Fire, so read a gap under 2% as a tie. [See the limits](#method).' },

      { id: 'c-group', group: 'test', title: 'Frost with Missile Barrage is the group spec, by a close margin',
        body: ['At the calculator defaults, before racials, Frost with Barrage (18/3/30) does 534 dps, 6.1% ahead of Fire with Arcane Blast (19/31/1, 503), with Arcane with Ignite (31/19/1, 496) and Arcane (31/3/17, 486) behind. In a dice simulation of 1000 fights the lead is 5.7%. It is still a close call, because two untested numbers flip it.',
          'Each of these alone puts Fire with Arcane Blast first: Ice Lance with no spell power scaling, as the game\'s data reads ([test m4](#t4)); and Fingers of Frost not procing on a raid boss, which cannot be chilled, as the sim assumes it does ([test m30](#t30)), since Ice Lance on Fingers charges is 143 of Frost\'s 534 dps. Either one drops Frost with Barrage to third or lower, and Fire with Arcane Blast then leads Arcane with Ignite by only 1.6%, a tie by this page\'s 2% rule. In fights under about 85 seconds the sim\'s deep Fire build, 0/35/16, edges ahead, by up to 2.5% ([see short fights](#c-short)).',
          'These narrow it without flipping it: high gear (700 spell power, 15% crit and 15% hit) leaves Frost 0.3% ahead, a tie; no boss partial resists 0.9%; 15% hit with a Moonkin 1.5%; 120 mp5 from gear 2.4%; 15% hit from gear 2.5%, because Fire with Arcane Blast has only 1 point of Elemental Precision; Ice Lance partially resisting 4.4% ([test m29](#t29)); and a Moonkin in your party 5.1%.',
          'Arcane Blast\'s tooltip reading ([test m8](#t8)) paired with either flip above, or with no boss partial resists, puts Arcane with Ignite first, by 1.7 to 2.3%. [This is test m4](#t4), and [test m30](#t30).'] },
      { id: 'c-arcane', group: 'test', title: 'Arcane Blast\'s stacks may not raise Arcane Missiles',
        body: 'Arcane Blast\'s tooltip says each stack raises "all your other spells" by 10%. The client\'s spell masks leave out Arcane Missiles, Blizzard and Flamestrike, and the calculator follows the client. If the tooltip is right, the Arcane builds gain 5 to 8% and Frost with Barrage still leads, by 2.8%. A second open question: whether Arcane Missiles end your Arcane Blast stacks. The rank 5 tooltip says the stacks last until any other damage spell is cast, and the sim ends them; only a reading of the client masks says no. If they do, the Arcane builds gain 1.5 to 2.3%, and no leader changes. [This is test m8](#t8), and [test m28](#t28).' },
      { id: 'c-lowranks', group: 'test', title: 'Low spell ranks lose strength far below your level',
        body: 'Blizzard\'s 1 October beta notes say spells cast from ranks far below your level get less from your spell damage and a lower chance to trigger talents: rank 1 Frostbolt at 60 has no chance at all to trigger Frostbite. They do not say where the cut starts. Forever\'s client stores every rank at full spell power scaling (Frostbolt rank 1: 0.407, against 0.163 in Classic), and a beta tester, DoubleZug, measured full scaling on healing ranks at levels 18 and 19 (via ForeverChanges, published before the 1 October build). This page casts your highest trained rank of each spell from 20, and so do the four page raid builds, so its numbers move only if the cut reaches ranks a few levels below you (your top Frostbolt rank is never more than 5 levels below you). Even if every low rank kept full strength, downranking would save at most 1.4% of leveling time from 20 to 60 in the model, and Blizzard\'s rule makes that smaller. [This is test m13](#t13).' },
      { id: 'c-break', group: 'test', title: 'How often damage breaks Frost Nova and Frostbite',
        body: 'Frost Nova\'s tooltip says damage may break it, and Frostbite\'s freeze carries the same break rule in the client\'s aura data. Nobody has measured how often. The models break either with a 50% chance on each damage event. It is the assumption that moves leveling most: if neither ever broke, Frost would level 19.2% faster; if both broke on every hit, 2.6% slower. Wand shots break them too. Frost stays first either way. [This is test m12](#t12).' },
      { id: 'c-drink', group: 'test', title: 'Rest speed depends on Spirit regen while you drink',
        body: 'The leveling model lets Spirit regen run while you eat and drink, as in Classic, where regen pauses only for 5 seconds after you spend mana, and drinking spends none. If it stops in Forever, Frost levels 4.6% slower and Fire 5.4%. The drink itself is the client\'s value (Conjured Crystal Water restores 4200 mana over 30 seconds); Wowhead\'s tooltips read 25/26 of that, which would cost 0.4%. [This is test m10](#t10).' },
      { id: 'c-tomes', group: 'test', title: 'The top-rank tomes have no known source in Forever',
        body: 'Frostbolt rank 11, Fireball rank 12 and Arcane Missiles rank 8 come from tomes. Their only known source is Ruins of Ahn\'Qiraj, which is not on the Forever roadmap, so the calculator uses trainer ranks. With the tomes, Frost with Barrage gains 7% (573 dps) and leads by 10%, and Arcane 31/3/17 passes Fire with Arcane Blast for second. [This is test m6](#t6).' },
      { id: 'c-resist', group: 'test', title: 'This page counts boss partial resists, so its damage reads lower than the Warlock page\'s',
        body: 'A level 63 boss resists about 6% of a spell\'s damage on average, unless the spell is binary. The ElliotWood sim counts this, and so does this calculator; the Warlock page does not, so a like-for-like Warlock number reads about 6% higher. Frostbolt and Blast Wave are binary and skip it, and the sim treats Ice Lance as binary too (an assumption, [test m29](#t29)), which helps Frost: without partial resists, Frost with Barrage still leads, but only by 0.9% (540 against 536). Nobody can test the resists before the raids open on 9 December. [See the limits](#method).' },
      { id: 'c-aoe', group: 'test', title: AOE.title, body: AOE.body },

      { id: 'c-gems', group: 'bust', title: 'Mana gems while leveling',
        body: 'Conjuring a gem costs more mana than it gives back: Agate 530 mana for 400, Jade 800 for 600, Citrine 1130 for 850, Ruby 1470 for 1100. On single mobs the leveling model never uses one. In a raid you conjure them before the pull, but at the calculator defaults Demonic and Dark Runes fill the shared cooldown first.' },
      { id: 'c-65', group: 'bust', title: 'A 65% Blizzard slow',
        body: 'Some published Forever AoE leveling guides plan around Improved Blizzard\'s Classic 65% slow. The Forever client has 15, 25 and 40% by rank, and Permafrost now lengthens chills by a percentage, so with both talents at 3/3 Blizzard chills for 50% over about 2 seconds, against 75% for 4.5 seconds in Classic. Cone of Cold went from 50% for 8 seconds to 40% for 6. [This is test m3](#t3).' },
      { id: 'c-fire-lvl', group: 'bust', title: 'Fire as a leveling spec',
        body: 'The best Fire-first order takes 16.0% longer than this page\'s order from 10 to 60 (121.1 hours of grinding against 104.4). It ties Frost at 10 to 19 and trails in every band after. Forever cut Fire\'s base damage hardest: Fireball\'s top rank does 425 to 541, 29% under Classic\'s 596 to 760. From 40 the model plays Fire as Scorch, Fire Blast and Heating Up Pyroblasts. Load it in the [talent builder](#builder) to compare.' },

      { id: 'c-personal', group: 'known', title: 'Improved Scorch and Winter\'s Chill are personal now',
        body: 'In Forever both only help the Mage who applies them: Fire Vulnerability raises your own Fire damage, and Winter\'s Chill your own Frostbolt and Ice Lance crit (+2% a stack, up to 5). The client data, Wowhead and the sim agree, so there is no shared Scorch Mage, and a Frost Mage buffs no one else. Every Fire Mage keeps their own 5 Scorch stacks. [Test m25](#t25) would confirm it in a group.' },
      { id: 'c-nowe', group: 'known', title: 'No Water Elemental',
        body: 'Forever\'s client has no Summon Water Elemental, so Frost has no pet. Several Season of Discovery spells still sit in the shared client and on Wowhead (Icy Veins, Arcane Barrage, Living Bomb, Deep Freeze, Frozen Orb), but ForeverChanges and the sim leave them out, and so does this page.' },
    ],

    // tests: [{ id, when, title, body }]; the checkbox id is the test id plus 'c'. Each id is 't' plus the number of the merged
    // test in mage-research/gap/tests.json (m4 is t4, the shell's id format); the visible label keeps 'm4'. m13 is rewritten
    // for level 30+ (again on 2 Oct 2026, after Blizzard's downrank rule) and m28 is new (both from the raid report); m31
    // and m32 come from readers. Ordered by how much the answer moves a verdict.
    tests: [
      { id: 't4', when: 'Test m4 · Level 20 and up · beta now', title: 'Ice Lance\'s spell power scaling.',
        body: 'Cast Ice Lance 30 times on a target that is not frozen, then add a known amount of spell damage (Minor Wizard Oil gives +8; +16 or more gives a cleaner result) and cast 30 more. Divide the change in the average non-crit hit by the spell damage you added. The game\'s data reads 0, the sim guesses 0.143, and 0.429 or 0.572 are as likely. At 0, Frost with Barrage drops to third and Fire with Arcane Blast leads, 1.6% ahead of Arcane with Ignite.' },
      { id: 't30', when: 'Test m30 · Level 60, a raid boss · raids (9 Dec)', title: 'Does Fingers of Frost proc on a raid boss?',
        body: 'With Fingers of Frost talented, cast 20 Frostbolts at a raid boss and count the Fingers of Frost buffs you gain: about 3 if it procs at 15% a landed chill, none if bosses block it, since they cannot be chilled. The sim and the calculator assume it procs. If it does not, Frost with Barrage falls to 450 dps and Fire with Arcane Blast leads, 1.6% ahead of Arcane with Ignite.' },
      { id: 't31', when: 'Test m31 · Level 29 and up · beta now', title: 'Can a Frostbolt in flight share a Fingers of Frost charge with Ice Lance?',
        body: 'With Fingers of Frost talented and one charge left, cast Frostbolt from range and cast Ice Lance while the Frostbolt is still in the air. If that Ice Lance hits for about four times its normal damage, one charge covered both spells, and Frost gets more from every proc than the calculator assumes: it spends each charge on one Ice Lance. Also note whether the charge disappears when the Frostbolt finishes casting or when it lands. Asked by a reader, WelshBen.' },
      { id: 't32', when: 'Test m32 · Level 20 and up · beta now', title: 'Can you shatter while a Frostbolt is still in the air?',
        body: 'Frost Nova a mob, cast Frostbolt (or Frostfire Bolt from 40), and cast Ice Lance the moment the Frostbolt finishes casting, while it is still in the air. Does that Ice Lance hit for about four times its normal damage even when the Frostbolt\'s hit breaks the root? And with Shatter talented, does the Frostbolt itself crit at the Shatter rate (the model gives it Shatter whenever the freeze still holds as it lands)? Do it 20 times, noting each Ice Lance hit, whether the root broke and each Frostbolt crit, then cast 20 Frostbolts and 20 Ice Lances at a mob that is not frozen and compare. The models land every spell the moment its cast ends, so in the leveling model the Frostbolt\'s hit can break the freeze before Ice Lance is cast, and this window is never credited: if it works, Frost could level faster than this page says; the model has not measured by how much. Fire Blast or Cone of Cold cast in the same window ask the same question. Asked by a reader, Pyrrolic_Victory.' },
      { id: 't3', when: 'Test m3 · Level 20 and up · beta now', title: 'Blizzard\'s chill, and how fast mobs run.',
        body: 'Time an unslowed melee mob running 25 yards to you: about 3.1 seconds means 8 yards a second. Then respec off the page plan into Permafrost 3/3 and Improved Blizzard 1/3, all 11 points at 20 (Improved Frostbolt 5, Permafrost 3, two more points in the top two rows, Improved Blizzard 1). Time the mob walking through your Blizzard, and note in the combat log when Chilled (12484) lands and fades. With Permafrost 3/3 the client predicts 25% slower at Improved Blizzard 1/3 and 50% at 3/3, for about 2 seconds. This decides AoE leveling.' },
      { id: 't12', when: 'Test m12 · Level 20 and up · beta now', title: 'How often damage breaks Frost Nova and Frostbite.',
        body: 'Frost Nova a group, step out, and hit the rooted mobs with Blizzard, Frostbolt or Arcane Explosion. In the combat log, count the damage events each rooted mob took and how many broke the root. Do the same for Frostbite freezes. The models break both on half of all damage events; if they never broke, Frost would level 19% faster.' },
      { id: 't13', when: 'Test m13 · Level 30 and up · beta now', title: 'How far below your level does a rank lose strength?',
        body: 'Blizzard says ranks far below your level get less from spell damage and a lower chance to trigger talents, but not where that starts. At a target dummy, cast each Frostbolt rank (ranks 1 to 5 at 30, learned at 4, 8, 14, 20 and 26) at least 30 times with and without a known change in spell damage (gear whose tooltip states it). Divide each rank\'s average non-crit gain by the spell damage change: full strength is 0.407, 0.489, 0.597, 0.706 and 0.814, and lower means that rank is cut at your level. Frostbolt is never partially resisted, so the numbers are clean. With Frostbite 3/3 and Fingers of Frost talented, also count freezes and Fingers of Frost procs over 100 casts of each rank: about 15 of each at full strength. This page casts your highest rank from 20, so its numbers move only if rank 5 reads below 0.814.' },
      { id: 't16', when: 'Test m16 · Level 10 and up · beta now', title: 'How much health normal mobs have, and how hard they hit.',
        body: 'Kill 5 normal mobs of exactly your level alone and add up the damage each took, minus overkill. Then let one melee mob hit you for 30 seconds with no shield and note the damage taken and your armor. The models use the Warlock page\'s curves: 608 health and 14 damage a second at level 20. Every leveling hour on both pages rides on these.' },
      { id: 't10', when: 'Test m10 · Level 20 and up · beta now', title: 'Drinking speed, and Spirit regen while you drink.',
        body: 'From low mana, wait 6 seconds, then drink one Conjured Purified Water for its full 24 seconds and note the mana gained. Then sit 24 seconds without drinking and note the Spirit regen alone. About 835 (the client) or 803 (Wowhead) plus the Spirit amount means regen runs while you drink, as the model assumes. Without it, Frost levels about 5% slower.' },
      { id: 't8', when: 'Test m8 · Level 20 and up · beta now', title: 'Does Arcane Blast raise Arcane Missiles?',
        body: 'Cast Arcane Missiles 10 times with no Arcane Blast stacks, then 10 times after 3 or 4 stacks, and compare the average non-crit missile. Repeat with Frostbolt and with Blizzard ticks. The client says the stacks skip Missiles and Blizzard (Frostbolt should rise 10% a stack); the tooltip says all your other spells. It reorders the Arcane raid builds.' },
      { id: 't29', when: 'Test m29 · Level 60, a raid boss · raids (9 Dec)', title: 'Does Ice Lance partially resist?',
        body: 'On a level 63 raid boss, cast Ice Lance at a target that is not frozen and read the combat log: any "resisted" amount on a hit means it partially resists. Compare with Frostbolt, which never shows one. The sim treats Ice Lance as binary; if it is not, Frost with Barrage loses about 8 dps and still leads by 4.4%.' },
      { id: 't28', when: 'Test m28 · Level 20 and up · beta now', title: 'Do Arcane Missiles end your Arcane Blast stacks?',
        body: 'Build 2 Arcane Blast stacks, then cast Arcane Missiles (a Missile Barrage proc or a plain cast). Check whether the Arcane Blast buff is gone, as the rank 5 tooltip and the sim say, or still up, as a reading of the client masks suggests, and whether the next Arcane Blast costs the base amount again. It moves the Arcane builds by 1.5 to 2.3%.' },
      { id: 't14', when: 'Test m14 · Any level · beta now', title: 'Does the five-second rule exist?',
        body: 'Stop casting for 6 seconds and note the mana you gain over the next 10. Then cast one cheap spell and note the mana gained over the next 4 seconds without casting; repeat 5 times. Nothing in the second step means the rule holds, as every model here assumes. If Spirit regen ran while casting, every mana number on this page would move.' },
      { id: 't5', when: 'Test m5 · Level 27 and up · beta now, Mage Armor at launch', title: 'Do Arcane Meditation and Mage Armor add up?',
        body: 'With Arcane Meditation 3/3, compare the mana you gain in the 4 seconds after a cast with your regen after 6 seconds of not casting: about half means the talent works. At 34, add Mage Armor and repeat: about full regen means they add, as the sim assumes; about half means they do not. If they do not, Fire with Arcane Blast loses about 3% in raids.' },
      { id: 't7', when: 'Test m7 · Level 20 and up · beta now', title: 'How much mana Evocation returns.',
        body: 'Note Spirit and mp5, spend mana to below half, wait 6 seconds, then channel Evocation for the full 8 seconds and note the mana gained. The sim\'s formula is 800 + 16 x Spirit + 1.6 x mp5. Half of that would cost Fire with Arcane Blast 1.7% in raids and the sim\'s Fire build 5.5%.' },
      { id: 't6', when: 'Test m6 · Level 60 · launch', title: 'Where the top-rank tomes come from.',
        body: 'At launch, check whether a trainer teaches Frostbolt rank 11, Fireball rank 12 or Arcane Missiles rank 8, and watch loot for Tome of Frostbolt XI, Tome of Fireball XII and Tome of Arcane Missiles VIII. With them, Frost with Barrage gains 7% and leads by 10%.' },
      { id: 't18', when: 'Test m18 · Level 25 and up · beta now', title: 'Missile Barrage\'s real proc rate.',
        body: 'Cast Arcane Blast 200 times and count Missile Barrage procs, then Frostbolt 200 times. The tooltip says 40% and 20%. The talent row also carries a 50% chance that could halve both, which would cost the Arcane builds about 5%.' },
      { id: 't2', when: 'Test m2 · Level 13 and up · beta now', title: 'Do dungeon kills give experience?',
        body: 'Note the XP from a normal open-world mob of your level, then from 5 trash mobs of about your level inside a dungeon, with your group size. Zero means dungeons are for their quests only. If kills pay, a tanked AoE dungeon run is worth modeling; this page leaves it out until then.' },
      { id: 't1', when: 'Test m1 · Level 14 and up · beta now', title: 'Is there a hidden AoE target cap?',
        body: 'Gather 8 or more mobs into one clump, cast Arcane Explosion once, and count in the combat log how many different mobs it hit. From 20, do the same for one Blizzard tick. The client stores no cap for Mage area spells; a server cap would limit every AoE pull at that number.' },
      { id: 't9', when: 'Test m9 · Level 16 and up, Blizzard at 20 · beta now', title: 'Can Blizzard and Flamestrike ticks crit?',
        body: 'Cast Flamestrike 5 times (from 16) and look for critical burn ticks in the combat log; from 20, channel Blizzard 5 full times on a group and count critical ticks. Note when the first Blizzard tick lands and how many a channel makes (8 expected). The sim says ticks never crit; if they do, Ice Shards and Shatter count for AoE.' },
      { id: 't17', when: 'Test m17 · Level 17 and up · beta now', title: 'Do armor and Blizzard chills trigger Frostbite?',
        body: 'With Frostbite 3/3 and Frost Armor, let a melee mob hit you 40 times and count Frostbite freezes on it. With Improved Blizzard, count freezes per Blizzard tick on a pack. The models let every chill roll Frostbite: about 15% of chills should freeze.' },
      { id: 't11', when: 'Test m11 · Level 19 and up · beta now, two Fire Mages', title: 'Is Ignite shared, and does it roll?',
        body: 'Two Fire Mages crit the same target within 4 seconds: one Ignite each, or one that grows? Solo, land two crits within 2 seconds and add up the Ignite ticks: 40% of both crits means it rolls with no loss, as the models assume. Losing 30% would cost Fire with Arcane Blast 2.6%.' },
      { id: 't15', when: 'Test m15 · Level 10 and up · beta now', title: 'Your miss chance against mobs three levels up.',
        body: 'With no hit talents and no hit gear, cast 300 spells at mobs exactly 3 levels higher (rank 1 Frostbolt saves mana) and count full resists, then 100 at your own level. About 17% and 4% means the Classic table holds, and so does the 16% raid hit cap the calculator uses.' },
      { id: 't20', when: 'Test m20 · Level 10 and up · beta now', title: 'How open-world packs behave.',
        body: 'Pull one mob and count how many others join. Bring humanoids low and note when they run and whether they bring friends. Kite a pack 60 yards or more under Blizzard and see whether any mob gives up and runs home. Note how often two mobs stand close enough to pull together: that find time moves two-mob pulls at 60 from 2% ahead of single target to 13% behind.' },
      { id: 't21', when: 'Test m21 · Level 20 and up · beta now', title: 'Arcane Blast\'s cost at each stack.',
        body: 'Read Arcane Blast\'s mana cost at 0, 1, 2, 3 and 4 stacks, and the 0-stack cost at every level you reach (base mana is that cost divided by 0.15). Each stack should add 1.75 times the 0-stack cost, as the sim models.' },
      { id: 't22', when: 'Test m22 · Level 20 and up · beta now', title: 'Do Fireball and Pyroblast burns crit?',
        body: 'Cast each 20 times and look for critical periodic ticks in the combat log. The client flag says they can, and the models count it. It is a small share of Fire damage.' },
      { id: 't23', when: 'Test m23 · Any level · beta now', title: 'Do the racials match their tooltips?',
        body: 'Gnome: read a spell\'s cost with Eureka! up (10% lower since build 70009), and check that its +10% skips damage over time but still reaches Arcane Missiles and Blizzard, as Blizzard\'s 1 October notes say. A known issue in that build makes Eureka! miss some spells for some classes, so an odd result may be that bug. Undead: count Touch of the Grave procs over 100 damaging spells (about 10 expected), and over 100 wand shots (the model counts them too). Skyborne: note mana per second with Read Ley Line up, and how often you find a ley line. The race advice rests on these.' },
      { id: 't24', when: 'Test m24 · Level 28 and up · beta now', title: 'Do mana gems, runes and potions share a cooldown?',
        body: 'Use a Mana Agate, then check that a mana potion is still usable right away. At 60, check that a Mana Ruby locks Demonic Runes and the other gems for 2 minutes. The raid calculator gives potions their own cooldown and puts gems and runes on one shared cooldown.' },
      { id: 't19', when: 'Test m19 · Level 30 and up · beta now', title: 'Does Fingers of Frost shatter a whole Cone of Cold?',
        body: 'With a Fingers of Frost charge up, cast Cone of Cold on a group 20 times and count crits per target, then 20 times without. Every target at the frozen crit rate means it shatters the whole cast. The AoE model counts Fingers of Frost on Frostbolt and Ice Lance only.' },
      { id: 't25', when: 'Test m25 · Level 27 and up · beta now, two Mages', title: 'Is Fire Vulnerability personal?',
        body: 'Mage A stacks Fire Vulnerability on a target; compare Mage B\'s Fire damage on it with and without the stacks. No change confirms what the client, Wowhead and the sim already agree on: no shared Scorch Mage. (Winter\'s Chill, the same question for Frost, needs 35 Frost points.)' },
      { id: 't26', when: 'Test m26 · Level 16 and up · beta now', title: 'Does a second Flamestrike stop the first?',
        body: 'Cast Flamestrike on a pack, then a second one 4 seconds later, and check whether the first burn stops. The tooltip says one Flamestrike per Mage.' },
      { id: 't27', when: 'Test m27 · Level 60 · launch', title: 'How many bottles Conjure Water makes at 60.',
        body: 'Cast Conjure Water rank 7 and count the bottles: 10 is the client\'s base value, and 20 means a Season of Discovery passive is live. It sets how often you stop to conjure at 60.' },
    ],

    // proof tables: { title, intro, head: [...], rows: [[...], ...], so } and { intro, head, rows, note }
    proof: {
      rule: {
        title: 'What Forever changed, and why Frost comes out ahead',
        intro: 'Forever cut the Mage\'s ways to hold a pack and gave Frost a single-target freeze loop instead. Fire lost the most base damage. Values from the beta client (build 1.60.1.69893) against Classic Era.',
        head: ['Spell or talent', 'Classic', 'Forever', 'What it means here'],
        align: ['', '', '', ''],
        rows: [
          ['Blizzard chill, Improved Blizzard and Permafrost at 3/3', '75% slow for 4.5 s', '50% slow for about 2 s', 'A pack walks out of the storm before the channel ends'],
          ['Cone of Cold slow', '50% for 8 s', '40% for 6 s', 'Less time to get away once a pack reaches you'],
          ['Ice Lance (talent)', 'Not in the game', 'Instant, 4 times the damage on a frozen target', 'The core of Frost leveling from 20, and 143 of Frost\'s 534 raid dps'],
          ['Shatter', '+50% crit on frozen targets for 5 points', 'The same for 3 points', 'Cheaper on the way down the Frost tree'],
          ['Fingers of Frost (talent)', 'Not in the game', 'Chills have a 15% chance to make your next 2 spells treat the target as frozen', 'Frozen targets on demand, even on bosses, if it procs there as the sim assumes ([test m30](#t30))'],
          ['Missile Barrage (talent)', 'Not in the game', 'Arcane Blast (40%) or Fireball, Frostbolt, Frostfire Bolt (20%) make the next Arcane Missiles free and twice as fast', '94 of Frost\'s 534 raid dps, and why every top raid build buys it'],
          ['Fireball, top rank', '596 to 760 damage', '425 to 541, 29% less', 'Fire lost the most; Frostbolt\'s top rank lost 11%'],
          ['Low spell ranks', 'Scaled down below level 20 (Frostbolt rank 1: 0.163)', 'Full scaling (0.407) measured at levels 18 and 19; Blizzard says ranks far below your level lose spell power and proc chance', 'This page casts your highest rank from 20; where the cut starts is [test m13](#t13)'],
        ],
        so: '**So:** Frost owns single-target leveling from 20, every top raid build buys Missile Barrage, and the Classic Blizzard grind loses the slow it was built on.',
      },
      // talentValues rows: generated from data/talents.json (per-rank values) and LevelingModel.SCORED / UNSCORED, with
      // the page plan's points at 60. Every number in the "Each rank" column is checked against data/talents.json.
      talentValues: {
        intro: 'What every talent does at each rank, from the beta client\'s talent curves. The last column says whether the talent builder\'s leveling score sees it: 43 of the 54 count, and the other 11 are listed with the reason.',
        head: ['Talent (ranks)', 'Tree', 'Each rank', 'Page plan at 60', 'Leveling score'],
        align: ['', '', '', 'r', ''],
        rows: [
        ['Wand Specialization (2)', 'Arcane', 'Wand damage +13/25%', '2', 'Yes'],
        ['Arcane Focus (5)', 'Arcane', 'Arcane spell hit +1/2/3/4/5%', '3', 'Yes'],
        ['Improved Channeling (5)', 'Arcane', 'Pushback protection: Arcane Missiles 20/40/60/80/100%, Arcane Blast 14/28/42/56/70%', '0', 'Yes'],
        ['Arcane Subtlety (2)', 'Arcane', 'Target resistances -8/15 for all your spells, Arcane threat -15/30%', '0', 'No: mob resistances are not modelled'],
        ['Magic Absorption (2)', 'Arcane', 'All resistances +5/10, and 1/2% mana back on a full resist', '0', 'No: resistances are not modelled'],
        ['Arcane Concentration (5)', 'Arcane', 'Clearcasting (next spell free) on 2/4/6/8/10% of hits, at most once a second', '5', 'Yes'],
        ['Arcane Resilience (2)', 'Arcane', 'Armor +25/50% of your Intellect', '0', 'No: mob damage is a flat rate, not armor-based'],
        ['Arcane Geometry (2)', 'Arcane', 'Arcane spell range +3/6 yd', '0', 'Yes'],
        ['Arcane Impact (3)', 'Arcane', 'Crit +2/4/6% on Arcane Blast, Arcane Explosion and Arcane Missiles', '0', 'Yes'],
        ['Arcane Blast (1)', 'Arcane', 'New spell: 2.5 s cast, 15% of base mana. Each cast: +10% damage to your other spells and +175% to its own cost, 4 stacks, 8 s', '0', 'Yes'],
        ['Arcane Shielding (2)', 'Arcane', 'Mana Shield mana per damage -17/33%, Mage Armor resistances +25/50%', '0', 'No: Mana Shield is not cast'],
        ['Improved Counterspell (2)', 'Arcane', 'Counterspell silences for 2/4 s', '0', 'No: the model has no caster mobs'],
        ['Arcane Meditation (3)', 'Arcane', '17/33/50% of mana regen continues while casting', '0', 'Yes'],
        ['Missile Barrage (1)', 'Arcane', 'Arcane Blast (40%) or Fireball, Frostbolt, Frostfire Bolt (20%): next Arcane Missiles free and 50% shorter, for 15 s', '0', 'Yes'],
        ['Presence of Mind (1)', 'Arcane', 'Next spell under 10 s cast is instant, 180 s cooldown', '0', 'Yes'],
        ['Arcane Mind (5)', 'Arcane', 'Intellect +2/4/6/8/10%, Arcane crit damage bonus +20/40/60/80/100%', '0', 'Yes'],
        ['Arcane Instability (3)', 'Arcane', 'Damage +1/2/3%, crit +1/2/3%', '0', 'Yes'],
        ['Arcane Power (1)', 'Arcane', '+30% damage and +30% mana cost for 15 s, 180 s cooldown', '0', 'Yes'],
        ['Wake of Fire (2)', 'Fire', 'Fire Blast cooldown -1/2 s; first Fire Blast within 30 s of a kill: crit +25/50%', '2', 'Yes'],
        ['Incineration (3)', 'Fire', 'Crit +2/4/6% on Fire Blast, Scorch, Arcane Blast and Ice Lance', '3', 'Yes'],
        ['Improved Fireball (5)', 'Fire', 'Fireball and Frostfire Bolt cast -0.1/0.2/0.3/0.4/0.5 s', '0', 'Yes'],
        ['Ignite (5)', 'Fire', 'Fire crits burn for another 8/16/24/32/40% over 4 s', '1', 'Yes'],
        ['Flame Throwing (2)', 'Fire', 'Fire spell range +3/6 yd', '0', 'Yes'],
        ['Impact (3)', 'Fire', 'Fire spells: 3/7/10% chance to stun for 2 s', '0', 'Yes'],
        ['Burning Soul (3)', 'Fire', 'Pushback protection 23/47/70%, Fire threat -10/20/30%', '0', 'Yes'],
        ['Improved Flamestrike (3)', 'Fire', 'Flamestrike crit +5/10/15%', '0', 'No: area spell (the AoE model)'],
        ['Pyroblast (1)', 'Fire', 'New spell: 6 s cast, 8 ranks, spell power x1.0 plus 0.15 a burn tick', '0', 'Yes'],
        ['Improved Scorch (3)', 'Fire', 'Scorch applies Fire Vulnerability 33/67/100% of the time: +3% your Fire damage a stack, 5 stacks', '0', 'Yes'],
        ['Improved Fire Ward (2)', 'Fire', 'Fire Ward reflects 10/20%', '0', 'No: the model has no caster mobs'],
        ['Heating Up (1)', 'Fire', 'Fire crits: Pyroblast cast -25% a stack, 3 stacks, 20 s', '0', 'Yes'],
        ['Master of Elements (3)', 'Fire', '10/20/30% of base cost back on a Fire or Frost crit', '0', 'Yes'],
        ['Critical Mass (3)', 'Fire', 'Fire crit +2/4/6%', '0', 'Yes'],
        ['Blast Wave (1)', 'Fire', 'Instant blast with a 50% daze for 6 s, 45 s cooldown, 5 ranks', '0', 'Yes'],
        ['Fire Power (5)', 'Fire', 'Fire damage +2/4/6/8/10%, burns included', '0', 'Yes'],
        ['Combustion (1)', 'Fire', '+10% Fire crit for each Fire hit, until 3 Fire crits, 180 s cooldown', '0', 'Yes'],
        ['Frost Warding (2)', 'Frost', 'Frost and Ice Armor +15/30%, Frost Ward reflects 10/20%', '0', 'No: mob damage is a flat rate, not armor-based'],
        ['Improved Frostbolt (5)', 'Frost', 'Frostbolt cast -0.1/0.2/0.3/0.4/0.5 s', '5', 'Yes'],
        ['Elemental Precision (5)', 'Frost', 'Fire and Frost spell hit +1/2/3/4/5%', '3', 'Yes'],
        ['Ice Shards (5)', 'Frost', 'Frost crit damage bonus +20/40/60/80/100%', '5', 'Yes'],
        ['Permafrost (3)', 'Frost', 'Chills last 11/22/33% longer and slow 3/7/10% more', '0', 'Yes'],
        ['Improved Frost Nova (2)', 'Frost', 'Frost Nova cooldown -2/4 s', '0', 'Yes'],
        ['Frostbite (3)', 'Frost', 'Each chill has a 5/10/15% chance to freeze the target for 5 s', '3', 'Yes'],
        ['Piercing Ice (3)', 'Frost', 'Frost damage +2/4/6%', '3', 'Yes'],
        ['Frost Channeling (3)', 'Frost', 'Frost spell cost -5/10/15%, Frost threat -10/20/30%', '3', 'Yes'],
        ['Ice Lance (1)', 'Frost', 'New spell: instant, +300% damage (4 times) on a frozen target, 6 ranks. Spell power scaling unknown (test m4)', '1', 'Yes'],
        ['Improved Blizzard (3)', 'Frost', 'Blizzard chills, slowing 15/25/40%', '0', 'No: area spell (the AoE model)'],
        ['Arctic Reach (2)', 'Frost', 'Frostbolt and Blizzard range +10/20%, Frost Nova and Cone of Cold radius +10/20%', '2', 'Yes'],
        ['Ice Block (1)', 'Frost', '10 s immunity, 300 s cooldown', '0', 'No: defensive'],
        ['Shatter (3)', 'Frost', 'Crit +17/33/50% against frozen targets', '3', 'Yes'],
        ['Improved Cone of Cold (3)', 'Frost', 'Cone of Cold damage +12/23/35%', '2', 'Yes'],
        ['Cold Snap (1)', 'Frost', 'Resets your other Frost cooldowns, 600 s cooldown', '0', 'No: 10 min cooldown, about one extra Frost Nova per 15 kills, not modelled'],
        ['Fingers of Frost (2)', 'Frost', 'Chills: 15% chance that your next 1/2 spells treat the target as frozen, 15 s', '2', 'Yes'],
        ['Winter\'s Chill (5)', 'Frost', 'Frost spells add a stack 20/40/60/80/100% of the time, up to 1/2/3/4/5 stacks: +2% crit a stack on your own Frostbolt and Ice Lance', '3', 'Yes'],
        ['Ice Barrier (1)', 'Frost', 'Absorb shield (431 at the first of 4 ranks), 60 s, 30 s cooldown. Casts are not delayed while it holds', '0', 'Yes'],
        ],
        note: 'At 60 the page plan kills in 19.80 seconds, and 20.25 without Arcane Concentration. Wand Specialization and Arcane Focus are in the plan to reach Arcane Concentration, and Improved Cone of Cold (59 and 60) changes nothing. Ice Block, Cold Snap and Ice Barrier are not in the plan. Arctic Reach scores through the longer Frostbolt pull only; its Frost Nova and Cone of Cold radius is not modeled.',
      },
    },

    // text slots, filled into elements with data-text. Supports **bold** and [label](#anchor or https://...). {name} is the class name.
    text: {
      title: 'Forever Mage Lab',
      eyebrow: 'WoW: Forever · Mage · beta data · v1.2 · 2 Oct 2026',
      lede: 'What to press, which talents to take and which race to play, at every level from 1 to 60. **The short answer:** level as Frost, and at 60 play Frost with Missile Barrage in groups, a close call over Fire.',
      trust: 'Built with Claude, with separate Claude sessions reviewing the models. Open source. [How it was checked](#method) · [What changed](#changelog)',
      navYou: 'Your {name}',
      youTitle: 'Your {name}',
      onramp: '**New to Mages?** You kill from range and run on mana. Frostbolt slows a mob so it reaches you late, Frost Nova roots it in place, and a frozen target takes four times the damage from Ice Lance. You drink between fights, and a mana potion on every cooldown cuts about 9% off your leveling time. Forever changed the class a lot: Ice Lance, Arcane Blast, Missile Barrage, Heating Up and Fingers of Frost are new, Blizzard\'s slow was cut hard, and there is no Water Elemental.',
      glossary: [
        ['Frozen', 'A target held by Frost Nova or a Frostbite freeze, or one your next spells treat as frozen thanks to Fingers of Frost. Ice Lance does four times its damage to it, and Shatter adds crit chance against it. The sim and this page assume bosses cannot be frozen, so in raids Fingers of Frost is the only way.'],
        ['Shatter', 'A Frost talent: +50% crit chance against frozen targets at 3 points. In Classic it took 5.'],
        ['Chill', 'A slow from a Frost effect: Frostbolt, Cone of Cold, Frostfire Bolt, Blizzard with Improved Blizzard, and Frost or Ice Armor on mobs that hit you. Frostbite and Fingers of Frost can trigger on any chill.'],
        ['Clearcasting', 'Arcane Concentration\'s proc: up to 10% of your spell hits make the next spell free, at most once a second.'],
        ['Downranking', 'Casting a lower rank of a spell because it costs less mana. A beta tester measured full spell power scaling on low ranks at levels 18 and 19, but Blizzard says ranks far below your level get less from spell damage and a lower chance to trigger talents. This page casts your highest rank from 20 ([test m13](#t13)).'],
        ['Five-second rule', 'Spirit regen stops for 5 seconds after you spend mana. Mage Armor (50%) and Arcane Meditation (up to 50%) keep part of it going while you cast. Nobody has measured the rule in Forever yet ([test m14](#t14)).'],
        ['Missile Barrage', 'An Arcane talent 15 points deep: Arcane Blast (40%) and Fireball, Frostbolt or Frostfire Bolt (20%) can make your next Arcane Missiles free and twice as fast.'],
        ['Spell power (SP)', 'The gear stat that makes every spell hit harder. Wands no longer gain from it in Forever.'],
        ['18/3/30', 'Talent points in Arcane, Fire and Frost, in that order.'],
      ],
      verdict: [
        { id: 'v-lvl1', k: 'Levels 10 to 19', body: '**Frostbolt and your wand, with Fire Blast from 14, and Improved Frostbolt first.** An Arcane wand build is about 4% faster at these levels, but they are under a tenth of your leveling time, so playing Arcane and respeccing at 20 saves only 0.36%.', link: ['#c-respec', 'Why not start Arcane'] },
        { id: 'v-lvl2', k: 'Levels 20 to 60', body: '**Frost, with Ice Lance on every freeze: this page\'s order takes about 104 hours of grinding from 10 to 60 in the model (kills only, no quest XP), against 114 for Arcane-first and 121 for Fire-first.** Frost Nova the mob when it closes and step back; from about 41, drop the wand and the step back and add Fire Blast on cooldown.', link: ['#c-frost', 'Why Frost levels fastest'] },
        { id: 'v-aoe', k: 'AoE leveling', body: AOE.verdict, link: ['#c-aoe', 'What the AoE model found'] },
        { id: 'v-group', k: 'Group at 60', body: '**A close call: Frost with Missile Barrage, 18/3/30, does 534 dps at the calculator defaults before racials, 6.1% ahead of Fire with Arcane Blast (19/31/1, 503).** Fire with Arcane Blast leads if Ice Lance has no spell power scaling or Fingers of Frost does not proc on bosses (both untested; by 1.6% over Arcane with Ignite, a near tie), and a deep Fire build edges ahead in fights under about 85 seconds.', link: ['#c-group', 'What decides the group spec'] },
        { id: 'v-race', k: 'Race', body: '**Race barely matters, so pick the one you like.** Undead levels about 3% faster and adds 1.6% in raids; every other race is within about 2% for leveling and 1.4% in raids.', link: ['#c-races', 'The race numbers'] },
        { id: 'v-dng', k: 'Dungeons', body: '**The first ones open at level 13**, all on one level line filtered to your faction. Whether dungeon kills give experience in Forever is untested ([test m2](#t2)), so the models leave dungeon leveling out.', link: ['#dungeons', 'See every dungeon by level'] },
      ],
      specsTitle: 'Specs for 60',
      specsIntro: 'Two for groups, one for playing alone. The group pick is a close call: two untested numbers flip it, and in short fights a deep Fire build edges ahead.',
      specsNote: '**How close is the group pick?** Frost with Missile Barrage leads Fire with Arcane Blast by 6.1% at the calculator defaults before racials, and by 5.7% in a cast-by-cast dice simulation of 1000 fights. Fire with Arcane Blast leads instead if Ice Lance has no spell power scaling ([test m4](#t4)) or if Fingers of Frost does not proc on raid bosses ([test m30](#t30)), though only 1.6% ahead of Arcane with Ignite. In fights under about 85 seconds the sim\'s deep Fire build (0/35/16) edges ahead, by up to 2.5%. High gear (700 spell power, 15% crit and 15% hit) narrows Frost\'s lead to 0.3%, a tie; no boss partial resists to 0.9%; a Moonkin in your party plus 15% hit from gear to 1.5%; 15% hit alone to 2.5%; a Moonkin alone to 5.1%. All four page builds cast top ranks, so Blizzard\'s new rule on low ranks moves none of them ([test m13](#t13)). [All of it in the proof](#c-group).',
      raidIntro: 'By default: one level 63 boss for 5 minutes, at the Warlock page\'s gear point (spell power 500, 10% crit, 11% hit from gear), with Intellect 300 and Spirit 120. Consumables count: a Major Mana Potion, Demonic Runes, mana gems and a Mageblood Elixir, each with its cost in its hint. Raid buffs on: Greater Blessings of Wisdom and Kings, Mana Spring Totem, Prayer of Spirit and Gift of the Wild; a Moonkin in your party is a separate switch, off by default. You cast your highest trainer ranks, with no top-rank tomes, and the boss partially resists. The numbers in this page\'s text are before racials; the bars add the race you picked. Change anything and the ranking updates.',
      raidNote: 'Options tagged untested are open questions, each with its test. The two that matter most are Ice Lance\'s scaling ([test m4](#t4)) and Fingers of Frost on bosses ([test m30](#t30)): either one at its other value puts Fire with Arcane Blast first, and in fights under about 85 seconds the sim\'s deep Fire build edges ahead. **Damage here reads about 6% lower than on the Warlock page** for spells that can be partially resisted, because this page counts a level 63 boss\'s partial resists, as the ElliotWood sim does. Read a gap under 2% as a tie: a dice simulation agrees within 1% for the four page builds at 5 minutes, but plans that wait for mana read 2 to 5% high and 60 second fights 3 to 7% high, most for Fire.',
      limits: '**Limits.** The beta is capped at level 30, so nobody has played a finished tree, and raids open on 9 December. These defaults are untested, and each is an option or a test. Raid: Ice Lance\'s spell power coefficient 0.143 ([m4](#t4)); Arcane Blast stacks that skip Arcane Missiles ([m8](#t8)) and that Missiles do not end ([m28](#t28)); Mage Armor and Arcane Meditation adding up ([m5](#t5)); the five-second rule and Classic Spirit regen ([m14](#t14)); the sim\'s Evocation formula ([m7](#t7)); Ignite rolling with no loss ([m11](#t11)); Missile Barrage at its tooltip rates ([m18](#t18)); highest ranks only from 20, which Blizzard\'s downrank rule backs ([m13](#t13)); no top-rank tomes ([m6](#t6)); a 16% hit cap ([m15](#t15)); 6% boss partial resists (no test before raids); Fingers of Frost procing on bosses, which cannot be chilled ([m30](#t30)), and Ice Lance never partially resisting ([m29](#t29)), both as the sim assumes; a second Paladin for Kings; a 57 dps wand while waiting for mana; and 4000 max health for Touch of the Grave. Leveling: damage breaking Frost Nova and Frostbite half the time ([m12](#t12)); Spirit regen while drinking ([m10](#t10)); the Warlock page\'s mob health and damage ([m16](#t16)); mobs running at 8 yards a second ([m3](#t3)); a 2 second step back after a root; gear adding 1 Intellect, 1 Stamina and half a Spirit a level; a 25 yard pull; armor chills rolling Frostbite ([m17](#t17)); half a second of pushback a hit; and 45 plus 5 x level XP a mob for the hour counts. All three models: every spell lands the moment its cast ends, with no travel time ([m31](#t31), [m32](#t32)). ' + AOE.limits + ' Numbers will move before 4 November. Corrections are welcome.',
      method: [
        'Spell data comes from the Forever beta client\'s own tables (build 1.60.1.69893): base damage, spell power coefficients, costs, cast times and learn levels for 166 spell ranks, cross-checked against Wowhead\'s Forever tooltips, ForeverChanges and the ElliotWood Forever sim. Later beta builds up to 70124 changed only Heating Up (then called Hot Streak), Wake of Fire, Ignite and Arcane Missiles\' line of sight, and the models use the newer values. The 1 October build returned Combustion to 3 charges, which the models now use; its other Mage changes (Improved Scorch and Winter\'s Chill without a resist roll, Eureka! off damage over time, low ranks cut far below your level) move no number here, and its balance pass on Comprehension scrolls, which the models leave out, may have changed the Coldflame Saber stats quoted on this page. Talent values are the client\'s per-rank curves for all 54 talents, matched against ForeverChanges\' rank texts. Racials come from Wowhead\'s Forever tooltips and ForeverChanges. Dungeon levels come from zockify.com, and Excavation Site: Wetlands from Blizzard\'s 1 October notes.',
        'Leveling runs through an expected-value fight simulator in 0.02 second steps. Hit and crit fold into every hit; Frostbite, Fingers of Frost, Missile Barrage and Heating Up procs count as they build up; the mob runs at you once your first spell lands; slows and roots hold it; melee hits push back your casts; and rest is the longer of eating and drinking, with potions, Evocation and racials used when they save time. For every build and level it searches 13 base rotations with modifiers (Frost Nova, stepping back, melee-range instants, a wand finish, lower ranks) and keeps the fastest. Against an exhaustive search on 212 cases, the largest gap was 0.000%. The page plan\'s talent order came from a search over every point, scored by mean seconds per kill from 10 to 60.',
        'The raid calculator is a mana-budget model: it finds the mix of spell cycles that does the most damage within the fight\'s time and mana, counting your pool, regen, raid buffs, potions, runes, gems, Evocation, and a wand while you wait for mana. A separate script plays each plan cast by cast with real dice over 1000 fights and lands within 1% of the calculator for the four page builds. On the ElliotWood Forever sim\'s own three builds and rotations, at matching stats, the calculator reads 0 to 3.6% above the sim (the sim still gives Combustion 4 charges, the calculator 3); the sim keeps a 1% miss floor, and its Frost build runs out of mana for 30 seconds of the 300.',
        AOE.method,
        'The research, models and this page were built with Claude, Anthropic\'s AI model. Separate Claude sessions then reviewed the models from their own checks, and their fixes are in. The calculator and the level planner run JavaScript ports of the Python models that reproduce them exactly: 63 raid cases, 2425 raid option checks, 569 stat weight checks and 771 leveling cases.',
      ],
      changelog: [
        '**v1.2, 2 Oct 2026.** Blizzard\'s 1 October beta notes. Combustion is back to 3 charges, so Fire with Arcane Blast drops to 503 dps and Frost with Missile Barrage now leads it by about 6% (5.7% in the dice). No boss partial resists and high gear no longer flip the group pick. Short fights now go to the sim\'s deep Fire build (under about 85 seconds in the dice, a near tie), not Fire with Arcane Blast, which never passes Frost in the dice. Ice Lance with no spell power scaling or Fingers of Frost not procing on bosses still put Fire with Arcane Blast first, by 1.6% over Arcane with Ignite. Blizzard says ranks far below your level lose spell power and proc chance, so the claim that low ranks may keep full strength is gone, test m13 is rewritten, and the calculator\'s low-rank switch is relabeled; by default this page never casts a lower rank from 20. Excavation Site: Wetlands is now 26 to 31. Hot Streak is now called Heating Up (old share links still work). The beta reaches 30, so seven more tests can be done now. A new test from a reader (m32): does Ice Lance shatter while a Frostbolt is still in the air?',
        '**v1.1, 1 Oct 2026.** A new test from a reader (m31): can a Frostbolt in flight share one Fingers of Frost charge with an Ice Lance? Deep links now stay on their target after the page finishes loading.',
        '**v1, 1 Oct 2026.** First release: a level planner with a talent order checked at every level, a talent builder that scores any leveling build, a raid calculator with stat weights and an item comparer, an AoE leveling check, and 30 in-game tests.',
      ],
      sources: [
        'Forever beta client tables, build 1.60.1.69893 (spells, talents, auras, items), from the [ElliotWood/Forever](https://github.com/ElliotWood/Forever) data cache',
        '[Wowhead Forever Mage talent calculator](https://www.wowhead.com/forever/talent-calc/mage) and Forever spell and item tooltips',
        '[ForeverChanges: Mage changes vs Classic](https://foreverchanges.pro/class/mage), talents, spellbook, racials and [patch notes](https://foreverchanges.pro/patch-notes)',
        '[ForeverChanges: downranking](https://foreverchanges.pro/downrank-calculator), with DoubleZug\'s beta measurements at levels 18 and 19',
        '[ElliotWood/Forever sim](https://github.com/ElliotWood/Forever): talent trees, client trait curves, spell data, and the raid cross-check',
        '[Icy Veins: Forever Mage overview](https://www.icy-veins.com/wow-forever/mage-class-overview)',
        '[Warcraft Tavern: Forever Mage guide](https://www.warcrafttavern.com/forever/guides/mage)',
        '[zockify: Forever dungeons by level](https://www.zockify.com/forever/dungeons/)',
      ],
    },
  };

  if (inNode) module.exports = CLASS; else root.CLASS = CLASS;
})(this);
